=begin html

<p>foo</p>

<p>bar</p>

=end html

=begin some-format with some parameter

woohoo

=end some-format

=head1 Two C<=for> styles

=for text foo

=for text
foo

=head1 Expecting Text Item

=over 4

=item

This is an item in the middle of a block-quote, which should be allowed.

=item

We're also testing tagless item commands.

=back
