#! /usr/bin/perl
# MAN module tester.

#########################

use strict;
use warnings;

use lib q(t);
use Testhelper;

my @tests;

my $diff_pod_flags = " -I 'This file was generated by po4a' ";
push @tests,
  {
    'doc' => "po4a-translate discards the fuzzy translation (and report so)",
    'run' =>
"perl ../po4a-translate -f pod -k 0 -m t-07-discard/pod -p t-07-discard/pod.po -l tmp/pod.fr",
    'test' => "diff -u t-07-discard/pod.fr tmp/pod.fr $diff_pod_flags",
  };

run_all_tests(@tests);
0;
