# TeX module tester.

#########################

use strict;
use warnings;

use lib q(t);
use Testhelper;

my @tests;

push @tests,
  {
    'doc'       => "gettextize well a simple tex document",
    'normalize' => "-f latex t-19-tex/simple.tex",
  };
push @tests,
  {
    'run' => "cp t-19-tex/simple.fr.po tmp && chmod u+w tmp/simple.fr.po"
      . " && LC_ALL=C COLUMNS=80 perl ../po4a-updatepo -f latex -m t-19-tex/simple.tex -p tmp/simple.fr.po > tmp/simple-updatepo.out 2>&1",
    'test' =>
"diff -u -I '^\.* done\.' t-19-tex/simple-updatepo.out tmp/simple-updatepo.out "
      . "&& perl compare-po.pl t-19-tex/simple.fr.po tmp/simple.fr.po",
    'doc' => "updatepo for this document",
  };
push @tests,
  {
    'run' =>
"LC_ALL=C COLUMNS=80 perl ../po4a-translate -f latex -m t-19-tex/simple.tex -p t-19-tex/simple.fr.po -l tmp/simple.fr.tex > tmp/simple-translate.out 2>&1",
    'test' => "diff -u t-19-tex/simple-translate.out tmp/simple-translate.out "
      . "&& diff -u -I 'This file was generated by po4a' t-19-tex/simple.fr.tex tmp/simple.fr.tex",
    'doc' => "translate this document",
  };
push @tests,
  {
    'run' =>
"LC_ALL=C COLUMNS=80 perl ../po4a-gettextize -f latex -m t-19-tex/theorem.tex -p tmp/theorem.pot > tmp/theorem-gettextize.out 2>&1",
    'test' => "perl compare-po.pl t-19-tex/theorem.pot tmp/theorem.pot",
    'doc'  => "gettextize well a LaTeX document with theorem environments",
  };

run_all_tests(@tests);
0;
