#! /usr/bin/perl
# Man module tester.

#########################

use strict;
use warnings;

use lib q(t);
use Testhelper;

my @tests;
push @tests,
  {
    'format' => 'man',
    'input'  => 'fmt/man/quotes.man'
  },
  {
    'format' => 'man',
    'input'  => 'fmt/man/quoted-comment.man',
  },
  {
    'format' => 'man',
    'input'  => 'fmt/man/dots1.man',
  },
  {
    'format' => 'man',
    'input'  => 'fmt/man/dots-errors1.man',
    'error'  => 1,
  },
  {
    'format' => 'man',
    'input'  => 'fmt/man/dots-errors2.man',
    'error'  => 1,
  },
  {
    'format' => 'man',
    'input'  => 'fmt/man/dots-errors3.man',
    'error'  => 1,
  },
  {
    'format' => 'man',
    'input'  => 'fmt/man/dots2.man',
  },
  {
    'doc'    => 'null arguments and null paragraphs',
    'format' => 'man',
    'input'  => 'fmt/man/null.man',
  },
  {
    'doc'    => 'escaped newlines and tabs',
    'format' => 'man',
    'input'  => 'fmt/man/escapes.man',
  },
  {
    'format' => 'man',
    'input'  => 'fmt/man/fonts.man',

    #        'options' => '-o=debug=fonts -o=debug=pretrans',
  },
  {
    'format' => 'man',
    'input'  => 'fmt/man/mdoc.man',
  };

my $diff_pod_flags = " -I 'This file was generated by po4a' ";

# Quotes (4 tests)
my @ignored;
push @ignored,

  # tbl format
  {
    'run'   => "PATH/po4a-gettextize -f man -m t-11-man/tbl-textblock.1 -p tmp/tbl-textblock.pot 2>/dev/null",
    'tests' => ["PODIFF t-11-man/tbl-textblock.pot tmp/tbl-textblock.pot"],
    'doc'   => "Right handling of text blocs in tbl macros",
  },
  {
    'run'   => "PATH/po4a-gettextize -f man -m t-11-man/tbl-option-tab.1 -p tmp/tbl-option-tab.pot 2>/dev/null",
    'tests' => ["PODIFF t-11-man/tbl-option-tab.pot tmp/tbl-option-tab.pot"],
    'doc'   => "Handle tab option in tab macros",
  },
  {
    'run' =>
      "PATH/po4a-translate -f man -m t-11-man/tbl-option-tab.1 -p t-11-man/tbl-option-tab.fr.po -l tmp/tbl-option-tab.fr.1 2>/dev/null",
    'tests' => ["diff -u diff_pod_flags t-11-man/tbl-option-tab.fr.1 tmp/tbl-option-tab.fr.1"],
    'doc'   => "translate this document",
  },

  # Mixed mdoc and roff format
  {
    'run'   => "cp t-11-man/mixed.fr.po tmp/ && chmod u+w tmp/mixed.fr.po && PATH/po4a t-11-man/mixed.cfg",
    'tests' => [
        "PODIFF t-11-man/mixed.pot tmp/mixed.pot",
        "PODIFF t-11-man/mixed.fr.po tmp/mixed.fr.po",
        "PODIFF t-11-man/mixed1.fr tmp/mixed1.fr",
        "PODIFF t-11-man/mixed2.fr tmp/mixed2.fr",
        "PODIFF t-11-man/mixed3.fr tmp/mixed3.fr",
        "PODIFF t-11-man/mixed4.fr tmp/mixed4.fr"
    ],
    'doc' => "mixed config with roff and mdoc"
  },

  # Non breaking spaces (7 tests)
  {
    'run'   => "PATH/po4a-gettextize -f man -m t-11-man/spaces -p tmp/spaces.pot 2>/dev/null",
    'tests' => ["PODIFF t-11-man/spaces.pot tmp/spaces.pot"],
    'doc'   => "gettextize well non breaking spaces",
  },
  {
    'run' => "cp t-11-man/spaces.fr_latin1.po tmp/ && chmod u+w tmp/spaces.fr_latin1.po"
      . " && PATH/po4a-updatepo -f man -m t-11-man/spaces -p tmp/spaces.fr_latin1.po >/dev/null 2>&1 ",
    'tests' => ["PODIFF t-11-man/spaces.fr_latin1.po tmp/spaces.fr_latin1.po"],
    'doc'   => "updatepo for this document (fr ISO-8859-1)",
  },
  {
    'run' =>
      "PATH/po4a-translate -f man -m t-11-man/spaces -p t-11-man/spaces.fr_latin1.po -l tmp/spaces.fr_latin1 2>/dev/null",
    'tests' => ["diff -u diff_pod_flags t-11-man/spaces.fr_latin1 tmp/spaces.fr_latin1"],
    'doc'   => "translate this document (fr ISO-8859-1)",
  },
  {
    'run' => "cp t-11-man/spaces.fr_utf8.po tmp/ && chmod u+w tmp/spaces.fr_utf8.po"
      . " && PATH/po4a-updatepo -f man -m t-11-man/spaces -p tmp/spaces.fr_utf8.po >/dev/null 2>&1 ",
    'tests' => ["PODIFF t-11-man/spaces.fr_utf8.po tmp/spaces.fr_utf8.po"],
    'doc'   => "updatepo for this document (fr UTF-8)",
  },
  {
    'run'   => "PATH/po4a-translate -f man -m t-11-man/spaces -p t-11-man/spaces.fr_utf8.po -l tmp/spaces.fr_utf8",
    'tests' => ["diff -u diff_pod_flags t-11-man/spaces.fr_utf8 tmp/spaces.fr_utf8"],
    'doc'   => "translate this document (fr UTF-8)",
  },
  {
    'run' => "cp t-11-man/spaces.ja.po tmp/ && chmod u+w tmp/spaces.ja.po"
      . " && PATH/po4a-updatepo -f man -m t-11-man/spaces -p tmp/spaces.ja.po >/dev/null 2>&1 ",
    'tests' => ["PODIFF t-11-man/spaces.ja.po tmp/spaces.ja.po"],
    'doc'   => "updatepo for this document (ja EUC-JP)",
  },
  {
    'run'   => "PATH/po4a-translate -f man -m t-11-man/spaces -p t-11-man/spaces.ja.po -l tmp/spaces.ja",
    'tests' => ["diff -u diff_pod_flags t-11-man/spaces.ja tmp/spaces.ja"],
    'doc'   => "translate this document (ja EUC-JP)",
  },

  # Hyphens (4 tests)
  {
    'run' => "PATH/po4a-gettextize -f man -m t-11-man/hyphens.1 -p tmp/hyphens.pot -o groff_code=verbatim 2>/dev/null",
    'tests' => ["PODIFF t-11-man/hyphens.verbatim.pot tmp/hyphens.pot"],
    'doc'   => "gettextize well hyphens (verbatim)",
  },
  {
    'run' =>
      "PATH/po4a-translate -f man -m t-11-man/hyphens.1 -p t-11-man/hyphens.verbatim.fr.po -l tmp/hyphens.fr -o groff_code=verbatim 2>/dev/null",
    'tests' => ["diff -u diff_pod_flags t-11-man/hyphens.verbatim.fr tmp/hyphens.fr"],
    'doc'   => "translate this document",
  },
  {
    'run' => "PATH/po4a-gettextize -f man -m t-11-man/hyphens.1 -p tmp/hyphens.pot -o groff_code=translate 2>/dev/null",
    'tests' => ["PODIFF t-11-man/hyphens.translate.pot tmp/hyphens.pot"],
    'doc'   => "gettextize well hyphens (translate)",
  },
  {
    'run' =>
      "PATH/po4a-translate -f man -m t-11-man/hyphens.1 -p t-11-man/hyphens.translate.fr.po -l tmp/hyphens.fr -o groff_code=translate 2>/dev/null",
    'tests' => ["diff -u diff_pod_flags t-11-man/hyphens.translate.fr tmp/hyphens.fr"],
    'doc'   => "translate this document",
  },

  # Macros (2 tests)
  {
    'run'   => "PATH/po4a-gettextize -f man -m t-11-man/macros.1 -p tmp/macros.pot 2>/dev/null",
    'tests' => ["PODIFF -I^#: t-11-man/macros.pot tmp/macros.pot"],
    'doc'   => "check for correct handling of some macros",
  },
  {
    'run' => "PATH/po4a-translate -f man -m t-11-man/macros.1 -p t-11-man/macros.de.po -l tmp/macros.de.1 2>/dev/null",
    'tests' => ["diff -u diff_pod_flags t-11-man/macros.de.1 tmp/macros.de.1"],
    'doc'   => "translate this document",
  };

run_all_tests(@tests);
0;
