package Locale::Po4a::SimplePod;

use 5.16.0;
use strict;
use warnings;

use parent qw(Locale::Po4a::TransTractor);

use Locale::Po4a::SimplePod::Parser;

sub initialize {
    my $self = shift;
    $self->{parser} = Locale::Po4a::SimplePod::Parser->new($self);
}

sub read {
    my ( $self, $filename, $refname, $charset ) = @_;
    push @{ $self->{inputs} }, $filename;
}

sub parse {
    my $self = shift;
    $self->{parser}->parse_file($_) for @{ $self->{inputs} };
}

# We cannot use =begin since parsing this file with POD parser might cause
# some troubles.
sub docheader {
    return "=for comment
This file was generated by po4a.  Do not store it in version control system,
for example, but store the Gettext PO file used as source file by po4a.

"
}

1;

__END__

=head1 NAME

Locale::Po4a::SimplePod - convert POD data from/to PO files, with Pod::Simple

=head1 SYNOPSIS

  [po4a_paths] /path/to/pot $lang:/path/to/po
  [type:SimplePod] /path/to/source.pod $lang:/path/to/localized.pod

or

  [po4a_paths] /path/to/pot $lang:/path/to/po
  [po4a_alias:pod] SimplePod
  [type:pod] /path/to/source.pod $lang:/path/to/localized.pod

=head1 DESCRIPTION

This is a module to help the translation of documentation in the POD format
(the preferred language for documenting Perl) into other human languages.


=head1 STATUS OF THIS MODULE

This module is still newly developed, so it is considerably less stable than
L<Locale::Po4a::Pod>.  However, this module is intended to replace the current
L<Locale::Po4a::Pod> module.  The reason is that L<Pod::Parser>, which is used
by the current L<Locale::Po4a::Pod>, is now deprecated, and it is recommended
to use L<Pod::Simple> instead.  See also L<GitHub issue #256 "Consider
migrating away from deprecated
C<Pod::Parser>|https://github.com/mquinson/po4a/issues/256>.

=head1 TODO

Stripping indentation from verbatim blocks could be useful.  I'm considering
using the C<strip_verbatim_indent> function to control this behavior.

=head1 SEE ALSO

L<Pod::Simple>, L<Locale::Po4a::Pod>, L<Locale::Po4a::TransTractor>,
L<po4a(7)|po4a.7>, L<Locale::Po4a::SimplePod::Parser>.

=head1 AUTHORS

  gemmaro <gemmaro.dev@gmail.com>

=head1 COPYRIGHT AND LICENSE

  Copyright (C) 2025 gemmaro <gemmaro.dev@gmail.com>.

This program is free software; you may redistribute it and/or modify it
under the terms of GPL v2.0 or later (see the COPYING file).
