#!/bin/sh

MASTER=""
NAME=""
SECTION=""
PO=""
OPTIONS=""

usage () {
	echo "Usage : $(basename $0) -m POD_FILE -p PO_FILE [-o PO4A_OPT]"
}

while getopts m:p:o:h option; do
	case $option in
	m)
	    MASTER=$OPTARG
	    ;;
	p)
	    PO=$OPTARG
	    ;;
	o)
	    OPTIONS="$OPTIONS $OPTARG"
	    ;;
	h)
	    usage
	    exit 0
	    ;;
	[?])
	    usage 1>&2
	    exit 1
	    ;;
    esac
done

if [ -z $PO ] || [ -z $MASTER ]; then
    usage
    exit 1
fi

if [ ! -f $PO ]; then
    echo "Error: unable to find the file $PO."
    usage 
    exit 1
fi

if [ ! -f $MASTER ]; then
    echo "Error: unable to find the file $MASTER."
    usage
    exit 1
fi

# Can fail to retrieve the expected result with various files...
#NAME=$(basename $MASTER .pod | sed -e 's/\..//')
#SECTION=$(basename $MASTER .pod | sed -e 's/.*\.//')

po4a-translate -f pod -m $MASTER -p $PO -L UTF-8 $OPTIONS \
	| pod2man -r '' -c TRANSLATED -n $MASTER --utf8 \
	| man -l -

