.TH PO4AMAN-DISPLAY-PO 1 "2006-04-08" "Po4a Tools" "Po4a Tools"
.SH NAME
po4aman-display-po \- display a translated man page according to a PO

.SH SYNOPSIS
.B po4aman-display-po
.B \-p
.I PO_FILE
.RB [ \-m
.IR MASTER_FILE ]
.RB [ \-o
.IR PO4A_OPT ]

.SH DESCRIPTION
\fBpo4aman-display-po\fP can be used by a translator who wants to check
how the man page being translated in a PO will be displayed.

.SH OPTIONS
.TP
.BI "\-p " PO_FILE
The PO file containing the translations.
.TP
.BI "\-m " MASTER_FILE
The original man page.
It can be the absolute or relative path to the original man page (gzipped
or not), the name the man page or the name and section of the man page
(using the man.section format).
.br
When the master document is not provided with the \fB\-m\fP option,
\fBpo4aman-display-po\fP tries to find the original man page
based on the line reference of the first string in the PO.
.TP
.BI "\-o " PO4A_OPT
Some options to pass to \fBpo4a-translate\fP.

.SH AUTHOR
Thomas Huriaux
