.Dd Jun 03, 2006
.Os Debian
.Dt MDOC 1
.Sh NAME
.Nm mdoc
.Nd test man page in mdoc
.Sh SYNOPSIS
.Nm
.Bk
.Op Ar option ...
.Ek
.Sh DESCRIPTION
This manual page documents
.Nm ,
a fake program.
.Ss Sub-section
.Nm
and also another inline
.Xr command 1 Ns 's
argument.
.
Lets try some punctuation
.Pa /etc/texmf/updmap.d/ .
.Pp
test2
.Pa ~/.texmf-config/updmap.d ),
and
.Pa ~/.texmf-var/web2c/updmap.cfg ) ;
and
.Pa ~/.texmf-var/web2c/updmap.cfg ) .
.Sh AUTHORS
This manual page was written by
.An -nosplit
.An me
and
.An "m y" Aq self

And lets play with fonts
.br
.Fd #include <netdb.h> \ \ \fP/* Or <unistd.h> on some systems */
.Ft int
.Fn rcmd "char **ahost" "int inport"
.br
?
